export const LIFECYCLE_PHASES = ["plan", "implementation", "test", "review", "resolution", "rereview", "decision", "closeout"] as const;
export type LifecyclePhase = typeof LIFECYCLE_PHASES[number];
export type LifecycleIdentity = { project: string; lifecycleKey: string; lifecycleRootMemoryId: string; taskwarriorProject: string; taskwarriorTask: string; taskwarriorUuid: string; jiraKey: string; sourceRefs: string[]; priorArtifactIds: string[] };
const object = (value: unknown): Record<string, unknown> | null => value && typeof value === "object" && !Array.isArray(value) ? value as Record<string, unknown> : null;
const text = (value: unknown) => typeof value === "string" ? value.trim() : "";
const clean = (value: unknown, maximum = 128_000) => typeof value === "string" ? value.replace(/(?:authorization|token|secret|password)\s*[:=]\s*\S+/gi, "[redacted]").slice(0, maximum) : "";
export function sanitizeLifecycleError(code: string, _value: unknown) { return { code, message: `Lifecycle integration failed: ${code}.` }; }
const validIdentity = (value: unknown): value is LifecycleIdentity => { const i = object(value); return Boolean(i && ["project", "lifecycleKey", "lifecycleRootMemoryId", "taskwarriorProject", "taskwarriorTask", "taskwarriorUuid", "jiraKey"].every((key) => text(i[key]).length > 0) && Array.isArray(i.sourceRefs) && Array.isArray(i.priorArtifactIds)); };
export function validateLifecycleRequest(value: unknown): { valid: true; type: LifecyclePhase; identity: LifecycleIdentity; artifact: string } | { valid: false; error: ReturnType<typeof sanitizeLifecycleError> } {
 const input = object(value); const type = text(input?.type); const artifact = clean(input?.artifact);
 if (!input || !LIFECYCLE_PHASES.includes(type as LifecyclePhase) || !validIdentity(input.identity) || !artifact || artifact.length > 128_000) return { valid: false, error: sanitizeLifecycleError("invalid_lifecycle_request", value) };
 return { valid: true, type: type as LifecyclePhase, identity: input.identity as LifecycleIdentity, artifact };
}
const requiredHeadings = ["source", "approved outcome", "scope", "non goals", "phase result", "changed", "decisions", "verification", "blockers", "residual risk", "prior artifact", "recommended next phase"];
export function artifactIsComplete(artifact: string) { const headings = artifact.toLowerCase().replace(/[^a-z0-9\n ]/g, " "); return requiredHeadings.every((heading) => headings.includes(heading)); }
export function buildLifecycleNonceMarker(input: { lifecycleKey: string; nonce: string; type: LifecyclePhase; jiraKey: string; taskwarriorUuid: string }) { return `<!-- ima-lifecycle verification: lifecycle_key=${input.lifecycleKey}; nonce=${input.nonce}; phase=${input.type}; jira_key=${input.jiraKey}; taskwarrior_uuid=${input.taskwarriorUuid}; outcome=completed -->`; }
const quoted = (value: string) => `'${value.replace(/'/g, "''")}'`;
export function buildLifecycleArtifact(input: { type: LifecyclePhase; identity: LifecycleIdentity; artifact: string; nonce: string }) {
 const i = input.identity; const refs = (values: string[]) => values.map((value) => `    - ${quoted(value)}`).join("\n") || "    - ''";
 return `---\nlifecycle:\n  project: ${quoted(i.project)}\n  lifecycle_key: ${quoted(i.lifecycleKey)}\n  lifecycle_root_memory_id: ${quoted(i.lifecycleRootMemoryId)}\n  taskwarrior_project: ${quoted(i.taskwarriorProject)}\n  taskwarrior_task: ${quoted(i.taskwarriorTask)}\n  taskwarrior_uuid: ${quoted(i.taskwarriorUuid)}\n  jira_key: ${quoted(i.jiraKey)}\n  source_refs:\n${refs(i.sourceRefs)}\n  phase: ${quoted(input.type)}\n  prior_artifact_ids:\n${refs(i.priorArtifactIds)}\n---\n\n${input.artifact.trim()}\n\n${buildLifecycleNonceMarker({ lifecycleKey: i.lifecycleKey, nonce: input.nonce, type: input.type, jiraKey: i.jiraKey, taskwarriorUuid: i.taskwarriorUuid })}\n`; }
export function validateVestigeSaveReceipt(envelope: unknown, expectedType: LifecyclePhase) { const e = object(envelope); const data = object(e?.data); return { accepted: Boolean(e?.ok === true && e?.command === "vestige.save" && data?.stored === true && data?.type === expectedType), artifactId: typeof data?.id === "string" ? data.id : null }; }
const strings = (value: unknown): string[] => typeof value === "string" ? [value] : Array.isArray(value) ? value.flatMap(strings) : value && typeof value === "object" ? Object.values(value).flatMap(strings) : [];
export function evaluateLifecycleRecall(input: { envelope: unknown; lifecycleKey: string; nonce: string; type: LifecyclePhase; jiraKey: string; taskwarriorUuid: string }) { const data = object(object(input.envelope)?.data); const results = Array.isArray(data?.results) ? data.results : []; const matched = results.map((result) => strings(result).join("\n")).find((value) => value.includes(input.lifecycleKey) && value.includes(input.nonce) && value.includes(input.type) && (value.includes(input.jiraKey) || value.includes(input.taskwarriorUuid)) && /\b(completed|success|outcome)\b/i.test(value)); const value = matched ?? ""; return { matched: Boolean(matched), lifecycleKeyMatched: Boolean(matched && value.includes(input.lifecycleKey)), nonceMatched: Boolean(matched && value.includes(input.nonce)), phaseMatched: Boolean(matched && value.includes(input.type)), sourceIdentityMatched: Boolean(matched && (value.includes(input.jiraKey) || value.includes(input.taskwarriorUuid))), outcomeMatched: Boolean(matched && /\b(completed|success|outcome)\b/i.test(value)), physicalShapeIgnored: true as const }; }
export function deriveLifecycleResult(input: { type: LifecyclePhase; lifecycleKey: string; receipt: ReturnType<typeof validateVestigeSaveReceipt>; recall: ReturnType<typeof evaluateLifecycleRecall>; error?: string }) { const completed = input.receipt.accepted && input.recall.matched && !input.error; return { schemaVersion: 1, status: completed ? "completed" as const : "failed" as const, phase: input.type, lifecycleKey: input.lifecycleKey, artifactId: input.receipt.artifactId, receiptAccepted: input.receipt.accepted, semanticRecall: input.recall, error: completed ? null : sanitizeLifecycleError(input.error ?? (!input.receipt.accepted ? "vestige_receipt_invalid" : "vestige_semantic_completion_unverified"), "") }; }
